<?php

namespace App\Http\Controllers;

use App\Announcement;
use App\Answer;
use App\Car;
use App\City;
use App\Condition;
use App\FuelType;
use App\Motor;
use App\Sale;
use App\Status;
use App\Type;
use App\User;
use App\Who;
use App\Year;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return false|\Illuminate\Contracts\Foundation\Application
     */
    public function index()
    {
//        session()->forget('send_flash');
//        $this->addItems();

//        for($i=21; $i < 121; $i++) {
//            Answer::create([
//                'announcement_id' => 6,
//                'user_id' => 7,
//                'which' => 'Orjinal',
//                'price' => mt_rand(0, 999),
//                'seen' => null,
//            ]);
//        }

        $cars= Car::all();
        $sales = Sale::all();

        if( ! $cars ) return false;

        return view('home', [
            'cars' => $cars,
            'sales' => $sales
        ]);
    }

    public function addItems()
    {
        $cars = [
            ['image' => 'alfaromeo.png',  'name' => 'Alfa Romeo', 'title' => 'alfaromeo'],
            ['image' => 'astonmartin.png',  'name' => 'Aston Martin', 'title' => 'astonmartin'],
            ['image' => 'atv.png',  'name' => 'Atv', 'title' => 'atv'],
            ['image' => 'audi.png',  'name' => 'Audi', 'title' => 'audi'],
            ['image' => 'baic.png',  'name' => 'Baic', 'title' => 'baic'],
            ['image' => 'bajaj.png',  'name' => 'Bajaj', 'title' => 'bajaj'],
            ['image' => 'bentley.png',  'name' => 'Bentley', 'title' => 'bentley'],
            ['image' => 'bmc.png',  'name' => 'BMC', 'title' => 'bmc'],
            ['image' => 'bmw.png',  'name' => 'BMW', 'title' => 'bmw'],
            ['image' => 'bmwalpina.jpg',  'name' => 'Bmw Alpina', 'title' => 'bmwalpina'],
            ['image' => 'brilliance.png',  'name' => 'Brilliance', 'title' => 'brilliance'],
            ['image' => 'buick.png',  'name' => 'Buick', 'title' => 'buick'],
            ['image' => 'byd.png',  'name' => 'Byd', 'title' => 'byd'],
            ['image' => 'cadillac.png',  'name' => 'Cadillac', 'title' => 'cadillac'],
            ['image' => 'changan.png',  'name' => 'Changan', 'title' => 'changan'],
            ['image' => 'chery.png',  'name' => 'Chery', 'title' => 'chery'],
            ['image' => 'chevrolet.png',  'name' => 'Chevrolet', 'title' => 'chevrolet'],
            ['image' => 'chrysler.png',  'name' => 'Chrysler', 'title' => 'chrysler'],
            ['image' => 'citroen.png',  'name' => 'Citroen', 'title' => 'citroen'],
            ['image' => 'dacia.png',  'name' => 'Dacia', 'title' => 'dacia'],
            ['image' => 'daewoo.png',  'name' => 'Daewoo', 'title' => 'daewoo'],
            ['image' => 'daf.png',  'name' => 'Daf', 'title' => 'daf'],
            ['image' => 'daihatsu.png',  'name' => 'Daihatsu', 'title' => 'daihatsu'],
            ['image' => 'dayun.jpg',  'name' => 'Dayun', 'title' => 'dayun'],
            ['image' => 'dnepr.png',  'name' => 'Dnepr', 'title' => 'dnepr'],
            ['image' => 'dodge.png',  'name' => 'Dodge', 'title' => 'dodge'],
            ['image' => 'dongfeng.png',  'name' => 'DongFeng', 'title' => 'dongfeng'],
            ['image' => 'ducati.png',  'name' => 'Ducati', 'title' => 'ducati'],
            ['image' => 'faw.png',  'name' => 'Faw', 'title' => 'faw'],
            ['image' => 'ferrary.png',  'name' => 'Ferrary', 'title' => 'ferrary'],
            ['image' => 'fiat.png',  'name' => 'Fiat', 'title' => 'fiat'],
            ['image' => 'ford.png',  'name' => 'Ford', 'title' => 'ford'],
            ['image' => 'foton.png',  'name' => 'Foton', 'title' => 'foton'],
            ['image' => 'gac.jpg',  'name' => 'Gac', 'title' => 'gac'],
            ['image' => 'gaz.jpeg',  'name' => 'Gaz', 'title' => 'gaz'],
            ['image' => 'geely.png',  'name' => 'Geely', 'title' => 'geely'],
            ['image' => 'gmc.jpg',  'name' => 'Gmc', 'title' => 'gmc'],
            ['image' => 'greatwall.jpg',  'name' => 'Great Wall', 'title' => 'greatwall'],
            ['image' => 'haojue.png',  'name' => 'Haojue', 'title' => 'haojue'],
            ['image' => 'harleydavidson.png',  'name' => 'Harley Davidson', 'title' => 'harleydavidson'],
            ['image' => 'haval.png',  'name' => 'Haval', 'title' => 'haval'],
            ['image' => 'honda.png', 'name' => 'Honda', 'title' => 'honda'],
            ['image' => 'howo.png', 'name' => 'Howo', 'title' => 'howo'],
            ['image' => 'hummer.jpg', 'name' => 'Hummer', 'title' => 'hummer'],
            ['image' => 'hyundai.png', 'name' => 'Hyundai', 'title' => 'hyundai'],
            ['image' => 'ij.jpg', 'name' => 'IJ', 'title' => 'ij'],
            ['image' => 'infiniti.png', 'name' => 'Infiniti', 'title' => 'infiniti'],
            ['image' => 'irankhodro.png', 'name' => 'Iran Khodro', 'title' => 'irankhodro'],
            ['image' => 'isuzu.jpg', 'name' => 'Isuzu', 'title' => 'isuzu'],
            ['image' => 'iveco.png', 'name' => 'Iveco', 'title' => 'iveco'],
            ['image' => 'jac.png', 'name' => 'JAC', 'title' => 'jac'],
            ['image' => 'jaguar.png', 'name' => 'Jaguar', 'title' => 'jaguar'],
            ['image' => 'jep.jpg', 'name' => 'Jep', 'title' => 'jep'],
            ['image' => 'jonway.jpg', 'name' => 'Jonway', 'title' => 'jonway'],
            ['image' => 'kamaz.jpg', 'name' => 'KamAz', 'title' => 'kamaz'],
            ['image' => 'kavz.png', 'name' => 'KAvZ', 'title' => 'kavz'],
            ['image' => 'kawaski.png', 'name' => 'Kawaski', 'title' => 'kawaski'],
            ['image' => 'khazar.png', 'name' => 'Khazar', 'title' => 'khazar'],
            ['image' => 'kia.png', 'name' => 'Kia', 'title' => 'kia'],
            ['image' => 'kinroad.png', 'name' => 'Kinroad', 'title' => 'kinroad'],
            ['image' => 'kraz.png', 'name' => 'KrAz', 'title' => 'kraz'],
            ['image' => 'ktm.png', 'name' => 'KTM', 'title' => 'ktm'],
            ['image' => 'kuba.jpg', 'name' => 'Kuba', 'title' => 'kuba'],
            ['image' => 'vaz.png', 'name' => 'Lada (VAZ)', 'title' => 'vaz'],
            ['image' => 'lamborghini.png', 'name' => 'Lamborghini', 'title' => 'lamborghini'],
            ['image' => 'landrover.png', 'name' => 'Land Rover', 'title' => 'landrover'],
            ['image' => 'lexus.png', 'name' => 'Lexus', 'title' => 'lexus'],
            ['image' => 'lifan.png', 'name' => 'Lifan', 'title' => 'lifan'],
            ['image' => 'lincoln.png', 'name' => 'Lincoln', 'title' => 'lincoln'],
            ['image' => 'luaz.jpg', 'name' => 'LuAz', 'title' => 'luaz'],
            ['image' => 'man.png', 'name' => 'Man', 'title' => 'man'],
            ['image' => 'maserati.png', 'name' => 'Maserati', 'title' => 'maserati'],
            ['image' => 'maz.png', 'name' => 'Maz', 'title' => 'maz'],
            ['image' => 'mazda.png', 'name' => 'Mazda', 'title' => 'mazda'],
            ['image' => 'mclaren.jpg', 'name' => 'McLaren', 'title' => 'mclaren'],
            ['image' => 'megelli.png', 'name' => 'Megelli', 'title' => 'megelli'],
            ['image' => 'mercedes.png', 'name' => 'Mercedes', 'title' => 'mercedes'],
            ['image' => 'maybach.png', 'name' => 'Mercedes-Maybach', 'title' => 'maybach'],
            ['image' => 'mg.png', 'name' => 'MG', 'title' => 'mg'],
            ['image' => 'mini.png', 'name' => 'Mini', 'title' => 'mini'],
            ['image' => 'minsk.png', 'name' => 'Minsk', 'title' => 'minsk'],
            ['image' => 'mitsubishi.png', 'name' => 'Mitsubishi', 'title' => 'mitsubishi'],
            ['image' => 'mondial.png', 'name' => 'Mondial', 'title' => 'mondial'],
            ['image' => 'moskvich.png', 'name' => 'moskvich', 'title' => 'moskvich'],
            ['image' => 'muravey.jpg', 'name' => 'Muravey', 'title' => 'muravey'],
            ['image' => 'nama.jpg', 'name' => 'Nama', 'title' => 'nama'],
            ['image' => 'neoplan.jpg', 'name' => 'Neoplan', 'title' => 'neoplan'],
            ['image' => 'neptun.jpg', 'name' => 'Neptun', 'title' => 'neptun'],
            ['image' => 'nissan.png', 'name' => 'Nissan', 'title' => 'nissan'],
            ['image' => 'opel.png', 'name' => 'Opel', 'title' => 'opel'],
            ['image' => 'otokar.png', 'name' => 'Otokar', 'title' => 'otokar'],
            ['image' => 'paz.png', 'name' => 'Paz', 'title' => 'paz'],
            ['image' => 'peugeot.png', 'name' => 'Peugeot', 'title' => 'peugeot'],
            ['image' => 'piaggio.jpg', 'name' => 'Piaggio', 'title' => 'piaggio'],
            ['image' => 'renault.png', 'name' => 'Pontiac', 'title' => 'renault'],
            ['image' => 'renault.png', 'name' => 'Porsche', 'title' => 'renault'],
            ['image' => 'renault.jpg', 'name' => 'Ravon', 'title' => 'renault'],
            ['image' => 'renault.png', 'name' => 'Renault', 'title' => 'renault'],
            ['image' => 'rollsroyce.png','name' => 'Rolls-Royce', 'title' => 'rollsroyce'],
            ['image' => 'rover.png','name' => 'Rover', 'title' => 'rover'],
            ['image' => 'saab.jpg', 'name' => 'Saab', 'title' => 'saab'],
            ['image' => 'saipa.jpg', 'name' => 'Saipa', 'title' => 'saipa'],
            ['image' => 'scania.jpg', 'name' => 'Scania', 'title' => 'scania'],
            ['image' => 'seat.png', 'name' => 'SEAT', 'title' => 'seat'],
            ['image' => 'shacman.png', 'name' => 'Shacman', 'title' => 'shacman'],
            ['image' => 'shaolin.png', 'name' => 'Shaolin', 'title' => 'shaolin'],
            ['image' => 'skoda.png', 'name' => 'Skoda', 'title' => 'skoda'],
            ['image' => 'smart.jpg', 'name' => 'Smart', 'title' => 'smart'],
            ['image' => 'ssangyong.png', 'name' => 'Ssang Yong', 'title' => 'ssangyong'],
            ['image' => 'subaru.png', 'name' => 'Subaru', 'title' => 'subaru'],
            ['image' => 'suzuki.png', 'name' => 'suzuki', 'title' => 'suzuki'],
            ['image' => 'tata.jpg', 'name' => 'Tata', 'title' => 'tata'],
            ['image' => 'tesla.png', 'name' => 'Tesla', 'title' => 'tesla'],
            ['image' => 'tofas.png', 'name' => 'Tofas', 'title' => 'tofas'],
            ['image' => 'toyota.png','name' => 'Toyota', 'title' => 'toyota'],
            ['image' => 'uaz.jpg', 'name' => 'UAZ', 'title' => 'uaz'],
            ['image' => 'ural.jpg', 'name' => 'Ural', 'title' => 'ural'],
            ['image' => 'vespa.png', 'name' => 'Vespa', 'title' => 'vespa'],
            ['image' => 'volkswagen.png','name' => 'Volkswagen', 'title' => 'volkswagen'],
            ['image' => 'volvo.png', 'name' => 'Volvo', 'title' => 'volvo'],
            ['image' => 'vosxod.png', 'name' => 'Vosxod', 'title' => 'vosxod'],
            ['image' => 'yamaha.jpg', 'name' => 'Yamaha', 'title' => 'yamaha'],
            ['image' => 'zaz.jpg', 'name' => 'ZAZ', 'title' => 'zaz'],
            ['image' => 'zil.png', 'name' => 'ZIL', 'title' => 'zil'],
            ['image' => 'zongshen.png', 'name' => 'Zongshen', 'title' => 'zongshen'],
            [ 'image' => 'zontes.jpg','name' => 'Zontes', 'title' => 'zontes'],
        ];
        foreach($cars as $c){
            Car::create([
                'title' => $c['title'],
                'name' => $c['name'],
                'image' => $c['image'],
            ]);
        }

        $types = [
            ['title' => '4C', 'parent_id' => 1],
            ['title' => 'Giulia', 'parent_id' => 1],
            ['title' => 'Giulietta', 'parent_id' => 1],
            ['title' => 'Mito', 'parent_id' => 1],
            ['title' => 'Stelvio', 'parent_id' => 1],

            ['title' => 'Rapide', 'parent_id' => 2],
            ['title' => 'Vanquish', 'parent_id' => 2],

            ['title' => '150', 'parent_id' => 3],
            ['title' => 'Hummer 250', 'parent_id' => 3],

            ['title' => '100', 'parent_id' => 4],
            ['title' => '80', 'parent_id' => 4],
            ['title' => 'A3', 'parent_id' => 4],
            ['title' => 'A4', 'parent_id' => 4],
            ['title' => 'A5', 'parent_id' => 4],
            ['title' => 'A6', 'parent_id' => 4],
            ['title' => 'A7', 'parent_id' => 4],
            ['title' => 'A8', 'parent_id' => 4],
            ['title' => 'Allroad', 'parent_id' => 4],
            ['title' => 'Q3', 'parent_id' => 4],
            ['title' => 'Q5', 'parent_id' => 4],
            ['title' => 'Q7', 'parent_id' => 4],
            ['title' => 'Q8', 'parent_id' => 4],
            ['title' => 'R8', 'parent_id' => 4],
            ['title' => 'RS7', 'parent_id' => 4],
            ['title' => 'S5', 'parent_id' => 4],
            ['title' => 'S6', 'parent_id' => 4],
            ['title' => 'S7', 'parent_id' => 4],
            ['title' => 'S8', 'parent_id' => 4],
            ['title' => 'TT', 'parent_id' => 4],
            ['title' => 'V8', 'parent_id' => 4],

            ['title' => 'A113/A115', 'parent_id' => 5],
            ['title' => 'M 20', 'parent_id' => 5],
            ['title' => 'M 60', 'parent_id' => 5],

            ['title' => 'Pulsar NS200', 'parent_id' => 6],
            ['title' => 'V', 'parent_id' => 6],

            ['title' => 'Bentayga', 'parent_id' => 7],
            ['title' => 'Continental', 'parent_id' => 7],
            ['title' => 'Flying Spur', 'parent_id' => 7],
            ['title' => 'Mulsanne', 'parent_id' => 7],

            ['title' => 'Pro 827', 'parent_id' => 8],
            ['title' => 'Pro 832', 'parent_id' => 8],

            ['title' => '120', 'parent_id' => 9],
            ['title' => '316', 'parent_id' => 9],
            ['title' => '318', 'parent_id' => 9],
            ['title' => '320', 'parent_id' => 9],
            ['title' => '320 GT', 'parent_id' => 9],
            ['title' => '323', 'parent_id' => 9],
            ['title' => '325', 'parent_id' => 9],
            ['title' => '328', 'parent_id' => 9],
            ['title' => '330', 'parent_id' => 9],
            ['title' => '335', 'parent_id' => 9],
            ['title' => '520', 'parent_id' => 9],
            ['title' => '523', 'parent_id' => 9],
            ['title' => '525', 'parent_id' => 9],
            ['title' => '528', 'parent_id' => 9],
            ['title' => '530', 'parent_id' => 9],
            ['title' => '535', 'parent_id' => 9],
            ['title' => '535 GT', 'parent_id' => 9],
            ['title' => '540', 'parent_id' => 9],
            ['title' => '545', 'parent_id' => 9],
            ['title' => '728', 'parent_id' => 9],
            ['title' => '730', 'parent_id' => 9],
            ['title' => '735', 'parent_id' => 9],
            ['title' => '740', 'parent_id' => 9],
            ['title' => '745', 'parent_id' => 9],
            ['title' => '750', 'parent_id' => 9],
            ['title' => '760', 'parent_id' => 9],
            ['title' => '630', 'parent_id' => 9],
            ['title' => '640', 'parent_id' => 9],
            ['title' => '645', 'parent_id' => 9],
            ['title' => '650', 'parent_id' => 9],
            ['title' => 'M4', 'parent_id' => 9],
            ['title' => 'M5', 'parent_id' => 9],
            ['title' => 'M6', 'parent_id' => 9],
            ['title' => 'M760', 'parent_id' => 9],
            ['title' => 'X5 M', 'parent_id' => 9],
            ['title' => 'X6 M', 'parent_id' => 9],
            ['title' => 'X1', 'parent_id' => 9],
            ['title' => 'X2', 'parent_id' => 9],
            ['title' => 'X3', 'parent_id' => 9],
            ['title' => 'X5', 'parent_id' => 9],
            ['title' => 'X6', 'parent_id' => 9],
            ['title' => 'X7', 'parent_id' => 9],
            ['title' => 'R 1200 GS', 'parent_id' => 9],
            ['title' => '420', 'parent_id' => 9],
            ['title' => '428', 'parent_id' => 9],
            ['title' => '430', 'parent_id' => 9],
            ['title' => 'i3', 'parent_id' => 9],
            ['title' => 'i8', 'parent_id' => 9],
            ['title' => '220', 'parent_id' => 9],
            ['title' => '228', 'parent_id' => 9],

            ['title' => 'B7', 'parent_id' => 10],

            ['title' => 'V7', 'parent_id' => 11],

            ['title' => 'Enclave', 'parent_id' => 12],
            ['title' => 'Encore', 'parent_id' => 12],
            ['title' => 'LaCrosse', 'parent_id' => 12],

            ['title' => 'F3', 'parent_id' => 13],
            ['title' => 'F6', 'parent_id' => 13],
            ['title' => 'S6', 'parent_id' => 13],

            ['title' => 'ATS', 'parent_id' => 14],
            ['title' => 'CT6', 'parent_id' => 14],
            ['title' => 'CTS', 'parent_id' => 14],
            ['title' => 'DTS', 'parent_id' => 14],
            ['title' => 'Escalade', 'parent_id' => 14],
            ['title' => 'Fleetwood', 'parent_id' => 14],
            ['title' => 'SRX', 'parent_id' => 14],
            ['title' => 'XTS', 'parent_id' => 14],

            ['title' => 'Alsvin', 'parent_id' => 15],
            ['title' => 'Alsvin V3', 'parent_id' => 15],
            ['title' => 'Alsvin V7', 'parent_id' => 15],
            ['title' => 'Benni', 'parent_id' => 15],
            ['title' => 'CS 15', 'parent_id' => 15],
            ['title' => 'CS 35', 'parent_id' => 15],
            ['title' => 'CS 75', 'parent_id' => 15],
            ['title' => 'CS 85', 'parent_id' => 15],
            ['title' => 'CS 95', 'parent_id' => 15],
            ['title' => 'CX 20', 'parent_id' => 15],
            ['title' => 'Eado', 'parent_id' => 15],
            ['title' => 'Eado DT', 'parent_id' => 15],
            ['title' => 'EU-Love', 'parent_id' => 15],
            ['title' => 'F70', 'parent_id' => 15],
            ['title' => 'Honor', 'parent_id' => 15],
            ['title' => 'Raeton', 'parent_id' => 15],
            ['title' => 'Star', 'parent_id' => 15],

            ['title' => 'A-15 Cowin/Amulet', 'parent_id' => 16],
            ['title' => 'A1-13/Kimo', 'parent_id' => 16],
            ['title' => 'Arrizo 5', 'parent_id' => 16],
            ['title' => 'Arrizo 7', 'parent_id' => 16],
            ['title' => 'B11/Eastar', 'parent_id' => 16],
            ['title' => 'E5', 'parent_id' => 16],
            ['title' => 'Fora', 'parent_id' => 16],
            ['title' => 'Fulwin 2', 'parent_id' => 16],
            ['title' => 'QQ', 'parent_id' => 16],
            ['title' => 'Tiggo', 'parent_id' => 16],
            ['title' => 'Tiggo 2', 'parent_id' => 16],

            ['title' => 'Aveo', 'parent_id' => 17],
            ['title' => 'Camaro', 'parent_id' => 17],
            ['title' => 'Caprice', 'parent_id' => 17],
            ['title' => 'Captiva', 'parent_id' => 17],
            ['title' => 'Cavalier', 'parent_id' => 17],
            ['title' => 'Cobalt', 'parent_id' => 17],
            ['title' => 'Cruze', 'parent_id' => 17],
            ['title' => 'Epica', 'parent_id' => 17],
            ['title' => 'Equinox', 'parent_id' => 17],
            ['title' => 'Express', 'parent_id' => 17],
            ['title' => 'Kalos', 'parent_id' => 17],
            ['title' => 'Lacetti', 'parent_id' => 17],
            ['title' => 'Lumina', 'parent_id' => 17],
            ['title' => 'Malibu', 'parent_id' => 17],
            ['title' => 'Niva', 'parent_id' => 17],
            ['title' => 'Orlando', 'parent_id' => 17],
            ['title' => 'Silverado', 'parent_id' => 17],
            ['title' => 'Spark', 'parent_id' => 17],
            ['title' => 'Suburban', 'parent_id' => 17],
            ['title' => 'Traverse', 'parent_id' => 17],
            ['title' => 'Trax', 'parent_id' => 17],
            ['title' => 'Volt', 'parent_id' => 17],

            ['title' => '200', 'parent_id' => 18],
            ['title' => '300C', 'parent_id' => 18],
            ['title' => 'Crossfire', 'parent_id' => 18],
            ['title' => 'Neon', 'parent_id' => 18],
            ['title' => 'PT Cruiser', 'parent_id' => 18],
            ['title' => 'Sebring', 'parent_id' => 18],
            ['title' => 'Town & Country', 'parent_id' => 18],
            ['title' => 'Voyager', 'parent_id' => 18],

            ['title' => 'C-Elysee', 'parent_id' => 19],
            ['title' => 'C3', 'parent_id' => 19],
            ['title' => 'C4', 'parent_id' => 19],
            ['title' => 'C5', 'parent_id' => 19],
            ['title' => 'DS5', 'parent_id' => 19],

            ['title' => 'Lodgy', 'parent_id' => 20],
            ['title' => 'Logan', 'parent_id' => 20],

            ['title' => 'BS090', 'parent_id' => 21],
            ['title' => 'Damas', 'parent_id' => 21],
            ['title' => 'Espero', 'parent_id' => 21],
            ['title' => 'Gentra', 'parent_id' => 21],
            ['title' => 'Labo', 'parent_id' => 21],
            ['title' => 'Lanos', 'parent_id' => 21],
            ['title' => 'Leganza', 'parent_id' => 21],
            ['title' => 'Matiz', 'parent_id' => 21],
            ['title' => 'Musso', 'parent_id' => 21],
            ['title' => 'Nexia', 'parent_id' => 21],
            ['title' => 'Nubira', 'parent_id' => 21],
            ['title' => 'Racer', 'parent_id' => 21],
            ['title' => 'Super Salon', 'parent_id' => 21],
            ['title' => 'Tico', 'parent_id' => 21],

            ['title' => '105XF', 'parent_id' => 22],
            ['title' => '85CF', 'parent_id' => 22],
            ['title' => '95XF', 'parent_id' => 22],
            ['title' => 'CF 290', 'parent_id' => 22],

            ['title' => 'Materia', 'parent_id' => 23],
            ['title' => 'Mira', 'parent_id' => 23],
            ['title' => 'Sirion', 'parent_id' => 23],
            ['title' => 'Terios', 'parent_id' => 23],

            ['title' => 'DY125-B', 'parent_id' => 24],
            ['title' => 'DY150-12', 'parent_id' => 24],

            ['title' => '11', 'parent_id' => 25],
            ['title' => 'K-750', 'parent_id' => 25],

            ['title' => 'Caliber', 'parent_id' => 26],
            ['title' => 'Challenger', 'parent_id' => 26],
            ['title' => 'Charger', 'parent_id' => 26],
            ['title' => 'Dart', 'parent_id' => 26],
            ['title' => 'Durango', 'parent_id' => 26],
            ['title' => 'Durango', 'parent_id' => 26],
            ['title' => 'Neon', 'parent_id' => 26],

            ['title' => 'DFL3310A13', 'parent_id' => 27],
            ['title' => 'EQ5081JSQG', 'parent_id' => 27],
            ['title' => 'Fengshen A30', 'parent_id' => 27],
            ['title' => 'Fengshen A30', 'parent_id' => 27],

            ['title' => '1100 EVO', 'parent_id' => 28],
            ['title' => '848 EVO Corse', 'parent_id' => 28],

            ['title' => 'CA6350', 'parent_id' => 29],
            ['title' => 'Bestune T33', 'parent_id' => 29],
            ['title' => 'Bestune T77', 'parent_id' => 29],
            ['title' => 'Bestune T99', 'parent_id' => 29],
            ['title' => 'Besturn B 50', 'parent_id' => 29],
            ['title' => 'Hongqi HS5', 'parent_id' => 29],
            ['title' => 'Hongqi HS7', 'parent_id' => 29],
            ['title' => 'Oley', 'parent_id' => 29],

            ['title' => '458 Italia', 'parent_id' => 30],
            ['title' => '458 Speciale', 'parent_id' => 30],
            ['title' => 'California', 'parent_id' => 30],

            ['title' => '500L', 'parent_id' => 31],
            ['title' => 'Albea', 'parent_id' => 31],
            ['title' => 'Bravo', 'parent_id' => 31],
            ['title' => 'Doblo', 'parent_id' => 31],
            ['title' => 'Egea', 'parent_id' => 31],
            ['title' => 'Fiorino', 'parent_id' => 31],
            ['title' => 'Linea', 'parent_id' => 31],
            ['title' => 'Punto', 'parent_id' => 31],
            ['title' => 'Qubo', 'parent_id' => 31],
            ['title' => 'Tempra', 'parent_id' => 31],
            ['title' => 'Ulysse', 'parent_id' => 31],

            ['title' => 'C-Max', 'parent_id' => 32],
            ['title' => 'Cargo', 'parent_id' => 32],
            ['title' => 'Courier', 'parent_id' => 32],
            ['title' => 'Edge', 'parent_id' => 32],
            ['title' => 'Escape', 'parent_id' => 32],
            ['title' => 'Escort', 'parent_id' => 32],
            ['title' => 'Expedition', 'parent_id' => 32],
            ['title' => 'Explorer', 'parent_id' => 32],
            ['title' => 'F-150', 'parent_id' => 32],
            ['title' => 'Fiesta', 'parent_id' => 32],
            ['title' => 'Focus', 'parent_id' => 32],
            ['title' => 'Fusion', 'parent_id' => 32],
            ['title' => 'Galaxy', 'parent_id' => 32],
            ['title' => 'Kuga', 'parent_id' => 32],
            ['title' => 'Maverick', 'parent_id' => 32],
            ['title' => 'Mercury', 'parent_id' => 32],
            ['title' => 'Mondeo', 'parent_id' => 32],
            ['title' => 'Mustang', 'parent_id' => 32],
            ['title' => 'Ranger', 'parent_id' => 32],
            ['title' => 'Scorpio', 'parent_id' => 32],
            ['title' => 'Tourneo Connect', 'parent_id' => 32],
            ['title' => 'Tourneo Custom', 'parent_id' => 32],
            ['title' => 'Transit', 'parent_id' => 32],

            ['title' => 'Aumark TX', 'parent_id' => 33],
            ['title' => 'Forland', 'parent_id' => 33],
            ['title' => 'Ollin', 'parent_id' => 33],
            ['title' => 'SUP', 'parent_id' => 33],

            ['title' => 'GA 5', 'parent_id' => 34],
            ['title' => 'GS 4', 'parent_id' => 34],
            ['title' => 'GS 5', 'parent_id' => 34],
            ['title' => 'GS 8', 'parent_id' => 34],

            ['title' => '24', 'parent_id' => 35],
            ['title' => '24-10', 'parent_id' => 35],
            ['title' => '2705', 'parent_id' => 35],
            ['title' => '2705-757', 'parent_id' => 35],
            ['title' => '2705-764', 'parent_id' => 35],
            ['title' => '27527-745', 'parent_id' => 35],
            ['title' => '2757', 'parent_id' => 35],
            ['title' => '3102', 'parent_id' => 35],
            ['title' => '31029', 'parent_id' => 35],
            ['title' => '3110', 'parent_id' => 35],
            ['title' => '31105', 'parent_id' => 35],
            ['title' => '3111', 'parent_id' => 35],
            ['title' => '32212', 'parent_id' => 35],
            ['title' => '3302-744', 'parent_id' => 35],
            ['title' => '330200', 'parent_id' => 35],
            ['title' => '330202-740', 'parent_id' => 35],
            ['title' => '33021', 'parent_id' => 35],
            ['title' => '33023-744', 'parent_id' => 35],
            ['title' => '330232-744', 'parent_id' => 35],
            ['title' => '33027-745', 'parent_id' => 35],
            ['title' => '33027-745', 'parent_id' => 35],
            ['title' => '3309-352', 'parent_id' => 35],
            ['title' => '52', 'parent_id' => 35],
            ['title' => '53', 'parent_id' => 35],
            ['title' => '66', 'parent_id' => 35],
            ['title' => '69', 'parent_id' => 35],
            ['title' => 'A21R22-03', 'parent_id' => 35],
            ['title' => 'C41R13', 'parent_id' => 35],
            ['title' => 'Gazon C41R33', 'parent_id' => 35],
            ['title' => 'M-20 Pobeda', 'parent_id' => 35],
            ['title' => 'M-21', 'parent_id' => 35],
            ['title' => 'Next А31R32', 'parent_id' => 35],
            ['title' => 'Next A21R22-30', 'parent_id' => 35],
            ['title' => 'Next A21R32-30', 'parent_id' => 35],
            ['title' => 'Next A22R22-30', 'parent_id' => 35],
            ['title' => 'Next A22R32', 'parent_id' => 35],
            ['title' => 'Next A31R22', 'parent_id' => 35],
            ['title' => 'Next A32R32-40', 'parent_id' => 35],
            ['title' => 'Next A64R42-10', 'parent_id' => 35],
            ['title' => 'Next A65R32-40', 'parent_id' => 35],
            ['title' => 'Sadko Next C41A23', 'parent_id' => 35],
            ['title' => 'Siber', 'parent_id' => 35],
            ['title' => 'Sobol', 'parent_id' => 35],
            ['title' => 'Vector Next', 'parent_id' => 35],

            ['title' => 'CK', 'parent_id' => 36],
            ['title' => 'Emgrand EC7', 'parent_id' => 36],
            ['title' => 'Emgrand EC8', 'parent_id' => 36],
            ['title' => 'MK', 'parent_id' => 36],
            ['title' => 'TX4', 'parent_id' => 36],

            ['title' => 'Acadia', 'parent_id' => 37],
            ['title' => 'Envoy', 'parent_id' => 37],
            ['title' => 'Safari', 'parent_id' => 37],
            ['title' => 'Sierra', 'parent_id' => 37],
            ['title' => 'Terrain', 'parent_id' => 37],
            ['title' => 'Yukon', 'parent_id' => 37],

            ['title' => 'Florid', 'parent_id' => 38],
            ['title' => 'Hover H3', 'parent_id' => 38],
            ['title' => 'Hover H5', 'parent_id' => 38],
            ['title' => 'Hover H6', 'parent_id' => 38],
            ['title' => 'Hover M2', 'parent_id' => 38],
            ['title' => 'Hover M4', 'parent_id' => 38],
            ['title' => 'Voleex C30', 'parent_id' => 38],
            ['title' => 'Voleex C50', 'parent_id' => 38],
            ['title' => 'Wingle', 'parent_id' => 38],

            ['title' => 'HJ100T-7C', 'parent_id' => 39],
            ['title' => 'HJ150-11A', 'parent_id' => 39],
            ['title' => 'HJ150-3C', 'parent_id' => 39],
            ['title' => 'HJ150-9', 'parent_id' => 39],
            ['title' => 'HJ150-9A', 'parent_id' => 39],
            ['title' => 'TR150S', 'parent_id' => 39],
            ['title' => 'TZ125', 'parent_id' => 39],

            ['title' => 'CVO Convertible', 'parent_id' => 40],
            ['title' => 'FXDR', 'parent_id' => 40],
            ['title' => 'Sportster Custom 1200', 'parent_id' => 40],
            ['title' => 'Touring Road King', 'parent_id' => 40],
            ['title' => 'Touring Street Glide', 'parent_id' => 40],
            ['title' => 'Harley-Davidson XL883N Sportster Iron 883', 'parent_id' => 40],

            ['title' => 'H2', 'parent_id' => 41],
            ['title' => 'H6', 'parent_id' => 41],
            ['title' => 'H7', 'parent_id' => 41],
            ['title' => 'H8', 'parent_id' => 41],
            ['title' => 'H9', 'parent_id' => 41],

            ['title' => 'Dio AF', 'parent_id' => 42],
            ['title' => 'GLX 1800', 'parent_id' => 42],
            ['title' => 'Accord', 'parent_id' => 42],
            ['title' => 'City', 'parent_id' => 42],
            ['title' => 'Civic', 'parent_id' => 42],
            ['title' => 'CR-V', 'parent_id' => 42],
            ['title' => 'Dio AF 35', 'parent_id' => 42],
            ['title' => 'Element', 'parent_id' => 42],
            ['title' => 'Insight', 'parent_id' => 42],
            ['title' => 'Passport', 'parent_id' => 42],
            ['title' => 'Pilot', 'parent_id' => 42],

            ['title' => '371', 'parent_id' => 43],
            ['title' => 'A7', 'parent_id' => 43],
            ['title' => 'Sinotruk', 'parent_id' => 43],

            ['title' => 'H2', 'parent_id' => 44],
            ['title' => 'H3', 'parent_id' => 44],

            ['title' => 'Accent', 'parent_id' => 45],
            ['title' => 'Azera', 'parent_id' => 45],
            ['title' => 'Chorus', 'parent_id' => 45],
            ['title' => 'County', 'parent_id' => 45],
            ['title' => 'Coupe', 'parent_id' => 45],
            ['title' => 'Creta', 'parent_id' => 45],
            ['title' => 'Elantra', 'parent_id' => 45],
            ['title' => 'Equus', 'parent_id' => 45],
            ['title' => 'Excel', 'parent_id' => 45],
            ['title' => 'Galloper', 'parent_id' => 45],
            ['title' => 'Genesis', 'parent_id' => 45],
            ['title' => 'Genesis Coupe', 'parent_id' => 45],
            ['title' => 'Getz', 'parent_id' => 45],
            ['title' => 'Grand Santa Fe', 'parent_id' => 45],
            ['title' => 'Grandeur', 'parent_id' => 45],
            ['title' => 'H 100', 'parent_id' => 45],
            ['title' => 'H 350', 'parent_id' => 45],
            ['title' => 'H-1', 'parent_id' => 45],
            ['title' => 'HD-120', 'parent_id' => 45],
            ['title' => 'HD-45', 'parent_id' => 45],
            ['title' => 'HD-65', 'parent_id' => 45],
            ['title' => 'HD-72', 'parent_id' => 45],
            ['title' => 'HD-78', 'parent_id' => 45],
            ['title' => 'i10', 'parent_id' => 45],
            ['title' => 'i20', 'parent_id' => 45],
            ['title' => 'i30', 'parent_id' => 45],
            ['title' => 'i40', 'parent_id' => 45],
            ['title' => 'ix35', 'parent_id' => 45],
            ['title' => 'ix55', 'parent_id' => 45],
            ['title' => 'Matrix', 'parent_id' => 45],
            ['title' => 'Palisade', 'parent_id' => 45],
            ['title' => 'Santa Fe', 'parent_id' => 45],
            ['title' => 'Solaris', 'parent_id' => 45],
            ['title' => 'Sonata', 'parent_id' => 45],
            ['title' => 'Terracan', 'parent_id' => 45],
            ['title' => 'Tucson', 'parent_id' => 45],
            ['title' => 'Veloster', 'parent_id' => 45],
            ['title' => 'Veracruz', 'parent_id' => 45],
            ['title' => 'XG', 'parent_id' => 45],

            ['title' => '57', 'parent_id' => 46],
            ['title' => '6.113-05 (Unker)', 'parent_id' => 46],
            ['title' => 'Planeta 2', 'parent_id' => 46],
            ['title' => 'Planeta 5', 'parent_id' => 46],
            ['title' => 'Planeta 7', 'parent_id' => 46],
            ['title' => 'Upiter 5', 'parent_id' => 46],
            ['title' => '2126 Oda', 'parent_id' => 46],
            ['title' => '2717', 'parent_id' => 46],
            ['title' => '27175', 'parent_id' => 46],

            ['title' => 'G25', 'parent_id' => 47],
            ['title' => 'G35', 'parent_id' => 47],
            ['title' => 'G35x', 'parent_id' => 47],
            ['title' => 'G37S', 'parent_id' => 47],
            ['title' => 'M35', 'parent_id' => 47],
            ['title' => 'M37S', 'parent_id' => 47],
            ['title' => 'EX25', 'parent_id' => 47],
            ['title' => 'EX35', 'parent_id' => 47],
            ['title' => 'FX35', 'parent_id' => 47],
            ['title' => 'FX37', 'parent_id' => 47],
            ['title' => 'FX45', 'parent_id' => 47],
            ['title' => 'JX35', 'parent_id' => 47],
            ['title' => 'Q45', 'parent_id' => 47],
            ['title' => 'Q50', 'parent_id' => 47],
            ['title' => 'Q50S', 'parent_id' => 47],
            ['title' => 'Q70', 'parent_id' => 47],
            ['title' => 'Q70S', 'parent_id' => 47],
            ['title' => 'QX4', 'parent_id' => 47],
            ['title' => 'QX56', 'parent_id' => 47],
            ['title' => 'QX60', 'parent_id' => 47],
            ['title' => 'QX70', 'parent_id' => 47],
            ['title' => 'QX80', 'parent_id' => 47],

            ['title' => 'Azsamand', 'parent_id' => 48],
            ['title' => 'Runna', 'parent_id' => 48],
            ['title' => 'Soren', 'parent_id' => 48],

            ['title' => 'Ecobus', 'parent_id' => 49],
            ['title' => 'MD 22 B', 'parent_id' => 49],
            ['title' => 'NHR 55 E', 'parent_id' => 49],
            ['title' => 'NKR 55 E', 'parent_id' => 49],
            ['title' => 'NKR 55 L', 'parent_id' => 49],
            ['title' => 'NP 37', 'parent_id' => 49],
            ['title' => 'NPR 66 L', 'parent_id' => 49],
            ['title' => 'NPR 71', 'parent_id' => 49],
            ['title' => 'NPR 75', 'parent_id' => 49],
            ['title' => 'Rodeo', 'parent_id' => 49],
            ['title' => 'Trooper', 'parent_id' => 49],
            ['title' => 'Turkuaz', 'parent_id' => 49],

            ['title' => '35C15', 'parent_id' => 50],
            ['title' => 'Daily 30-8', 'parent_id' => 50],
            ['title' => 'Daily 35C15VH', 'parent_id' => 50],
            ['title' => 'EuroStar', 'parent_id' => 50],
            ['title' => 'Otoyol', 'parent_id' => 50],
            ['title' => 'Stralis', 'parent_id' => 50],
            ['title' => 'Trakker', 'parent_id' => 50],

            ['title' => 'HFC1045KRD', 'parent_id' => 51],
            ['title' => 'HFC1061K5P', 'parent_id' => 51],
            ['title' => 'T8', 'parent_id' => 51],

            ['title' => 'E-Pace', 'parent_id' => 52],
            ['title' => 'F-Pace', 'parent_id' => 52],
            ['title' => 'F-Pace R', 'parent_id' => 52],
            ['title' => 'F-Type', 'parent_id' => 52],
            ['title' => 'F-Type R', 'parent_id' => 52],
            ['title' => 'XE', 'parent_id' => 52],
            ['title' => 'XF', 'parent_id' => 52],
            ['title' => 'XJ', 'parent_id' => 52],
            ['title' => 'XJ L', 'parent_id' => 52],

            ['title' => 'Cherokee', 'parent_id' => 53],
            ['title' => 'Commander', 'parent_id' => 53],
            ['title' => 'Compass', 'parent_id' => 53],
            ['title' => 'Grand Cherokee', 'parent_id' => 53],
            ['title' => 'Liberty', 'parent_id' => 53],
            ['title' => 'Patriot', 'parent_id' => 53],
            ['title' => 'Renegade', 'parent_id' => 53],
            ['title' => 'Wrangler', 'parent_id' => 53],

            ['title' => 'YY50QT-21B', 'parent_id' => 54],
            ['title' => 'YY50QT-6', 'parent_id' => 54],

            ['title' => '4308', 'parent_id' => 55],
            ['title' => '43101', 'parent_id' => 55],
            ['title' => '5320', 'parent_id' => 55],
            ['title' => '53202', 'parent_id' => 55],
            ['title' => '53212', 'parent_id' => 55],
            ['title' => '53213', 'parent_id' => 55],
            ['title' => '53215', 'parent_id' => 55],
            ['title' => '53229', 'parent_id' => 55],
            ['title' => '5410', 'parent_id' => 55],
            ['title' => '54112', 'parent_id' => 55],
            ['title' => '5511', 'parent_id' => 55],
            ['title' => '55111', 'parent_id' => 55],
            ['title' => '55115', 'parent_id' => 55],
            ['title' => '65115', 'parent_id' => 55],
            ['title' => '65117', 'parent_id' => 55],
            ['title' => '6520', 'parent_id' => 55],
            ['title' => '65201', 'parent_id' => 55],

            ['title' => '3270', 'parent_id' => 56],

            ['title' => 'Z1000', 'parent_id' => 57],
            ['title' => 'ZX-6R', 'parent_id' => 57],

            ['title' => 'LX', 'parent_id' => 58],
            ['title' => 'SD', 'parent_id' => 58],

            ['title' => 'Avella', 'parent_id' => 59],
            ['title' => 'Bongo', 'parent_id' => 59],
            ['title' => 'Cadenza', 'parent_id' => 59],
            ['title' => 'Carens', 'parent_id' => 59],
            ['title' => 'Carnival', 'parent_id' => 59],
            ['title' => 'Ceed', 'parent_id' => 59],
            ['title' => 'Cerato', 'parent_id' => 59],
            ['title' => 'Clarus', 'parent_id' => 59],
            ['title' => 'Credos', 'parent_id' => 59],
            ['title' => 'Joice', 'parent_id' => 59],
            ['title' => 'K2700', 'parent_id' => 59],
            ['title' => 'Koup', 'parent_id' => 59],
            ['title' => 'Magentis', 'parent_id' => 59],
            ['title' => 'Mohave', 'parent_id' => 59],
            ['title' => 'Opirus', 'parent_id' => 59],
            ['title' => 'Optima', 'parent_id' => 59],
            ['title' => 'Picanto', 'parent_id' => 59],
            ['title' => 'Pregio', 'parent_id' => 59],
            ['title' => 'Pride', 'parent_id' => 59],
            ['title' => 'Quoris', 'parent_id' => 59],
            ['title' => 'Rio', 'parent_id' => 59],
            ['title' => 'Rio X-Line', 'parent_id' => 59],
            ['title' => 'Sephia', 'parent_id' => 59],
            ['title' => 'Shuma', 'parent_id' => 59],
            ['title' => 'Sorento', 'parent_id' => 59],
            ['title' => 'Soul', 'parent_id' => 59],
            ['title' => 'Sportage', 'parent_id' => 59],
            ['title' => 'Stinger', 'parent_id' => 59],

            ['title' => 'XT150QT-8', 'parent_id' => 60],

            ['title' => '65053', 'parent_id' => 61],
            ['title' => '6511C4-082', 'parent_id' => 61],

            ['title' => '390 Duke', 'parent_id' => 62],

            ['title' => 'Dragon 50', 'parent_id' => 63],
            ['title' => 'Ege 50', 'parent_id' => 63],
            ['title' => 'Reiz 50', 'parent_id' => 63],

            ['title' => 'Vesta', 'parent_id' => 64],
            ['title' => 'Vesta Cross', 'parent_id' => 64],
            ['title' => 'Vesta SW', 'parent_id' => 64],
            ['title' => 'Vesta SW Cross', 'parent_id' => 64],
            ['title' => 'XRAY', 'parent_id' => 64],
            ['title' => 'XRAY Cross', 'parent_id' => 64],
            ['title' => '2101', 'parent_id' => 64],
            ['title' => '21011', 'parent_id' => 64],
            ['title' => '21013', 'parent_id' => 64],
            ['title' => '2102', 'parent_id' => 64],
            ['title' => '2103', 'parent_id' => 64],
            ['title' => '2104', 'parent_id' => 64],
            ['title' => '2105', 'parent_id' => 64],
            ['title' => '2106', 'parent_id' => 64],
            ['title' => '2107', 'parent_id' => 64],
            ['title' => '2108', 'parent_id' => 64],
            ['title' => '2109', 'parent_id' => 64],
            ['title' => '21099', 'parent_id' => 64],
            ['title' => '2110', 'parent_id' => 64],
            ['title' => '21103', 'parent_id' => 64],
            ['title' => '2111', 'parent_id' => 64],
            ['title' => '2112', 'parent_id' => 64],
            ['title' => '2113', 'parent_id' => 64],
            ['title' => '2114', 'parent_id' => 64],
            ['title' => '2115', 'parent_id' => 64],
            ['title' => 'Granta', 'parent_id' => 64],
            ['title' => 'Kalina', 'parent_id' => 64],
            ['title' => 'Largus', 'parent_id' => 64],
            ['title' => 'Niva', 'parent_id' => 64],
            ['title' => 'Oka', 'parent_id' => 64],
            ['title' => 'Priora', 'parent_id' => 64],

            ['title' => 'Aventador', 'parent_id' => 65],
            ['title' => 'Gallardo', 'parent_id' => 65],

            ['title' => 'Defender', 'parent_id' => 66],
            ['title' => 'Discovery', 'parent_id' => 66],
            ['title' => 'Discovery Sport', 'parent_id' => 66],
            ['title' => 'Freelander', 'parent_id' => 66],
            ['title' => 'Range Rover', 'parent_id' => 66],
            ['title' => 'RR Evoque', 'parent_id' => 66],
            ['title' => 'RR Sport', 'parent_id' => 66],
            ['title' => 'Velar', 'parent_id' => 66],

            ['title' => 'IS 200', 'parent_id' => 67],
            ['title' => 'IS 250', 'parent_id' => 67],
            ['title' => 'IS 300', 'parent_id' => 67],
            ['title' => 'GS 250', 'parent_id' => 67],
            ['title' => 'GS 300', 'parent_id' => 67],
            ['title' => 'GS 350', 'parent_id' => 67],
            ['title' => 'GS200T ', 'parent_id' => 67],
            ['title' => 'ES 250', 'parent_id' => 67],
            ['title' => 'ES 300', 'parent_id' => 67],
            ['title' => 'ES 350', 'parent_id' => 67],
            ['title' => 'LS 400', 'parent_id' => 67],
            ['title' => 'LS 460', 'parent_id' => 67],
            ['title' => 'LS 600 H', 'parent_id' => 67],
            ['title' => 'RX 200t', 'parent_id' => 67],
            ['title' => 'RX 300', 'parent_id' => 67],
            ['title' => 'RX 330', 'parent_id' => 67],
            ['title' => 'RX 350', 'parent_id' => 67],
            ['title' => 'RX 400 H', 'parent_id' => 67],
            ['title' => 'GX 460', 'parent_id' => 67],
            ['title' => 'GX 470', 'parent_id' => 67],
            ['title' => 'LX 450', 'parent_id' => 67],
            ['title' => 'LX 470', 'parent_id' => 67],
            ['title' => 'LX 570', 'parent_id' => 67],
            ['title' => 'CT 200 H', 'parent_id' => 67],
            ['title' => 'NX 200', 'parent_id' => 67],
            ['title' => 'NX 200T', 'parent_id' => 67],
            ['title' => 'NX 300H', 'parent_id' => 67],
            ['title' => 'NX300', 'parent_id' => 67],
            ['title' => 'LS 500', 'parent_id' => 67],

            ['title' => '320', 'parent_id' => 68],
            ['title' => '330', 'parent_id' => 68],
            ['title' => '520', 'parent_id' => 68],
            ['title' => '620', 'parent_id' => 68],
            ['title' => '720', 'parent_id' => 68],
            ['title' => '820', 'parent_id' => 68],
            ['title' => 'X60', 'parent_id' => 68],

            ['title' => 'MKX', 'parent_id' => 69],
            ['title' => 'Navigator', 'parent_id' => 69],
            ['title' => 'Towncar', 'parent_id' => 69],

            ['title' => '969M', 'parent_id' => 70],

            ['title' => '19372', 'parent_id' => 71],
            ['title' => '19463', 'parent_id' => 71],
            ['title' => '22.321', 'parent_id' => 71],
            ['title' => '26.403', 'parent_id' => 71],
            ['title' => 'F2000', 'parent_id' => 71],
            ['title' => 'TGA 18.440', 'parent_id' => 71],
            ['title' => 'TGA 33.480', 'parent_id' => 71],
            ['title' => 'TGA 410', 'parent_id' => 71],

            ['title' => 'Ghibli', 'parent_id' => 72],
            ['title' => 'GranTurismo', 'parent_id' => 72],
            ['title' => 'GranTurismo S', 'parent_id' => 72],
            ['title' => 'Quattroporte', 'parent_id' => 72],

            ['title' => '3577', 'parent_id' => 73],
            ['title' => '5337', 'parent_id' => 73],
            ['title' => '54323', 'parent_id' => 73],
            ['title' => '5549', 'parent_id' => 73],
            ['title' => '642208', 'parent_id' => 73],

            ['title' => '2', 'parent_id' => 74],
            ['title' => '3', 'parent_id' => 74],
            ['title' => '323', 'parent_id' => 74],
            ['title' => '6', 'parent_id' => 74],
            ['title' => '626', 'parent_id' => 74],
            ['title' => 'CX-5', 'parent_id' => 74],
            ['title' => 'CX-7', 'parent_id' => 74],
            ['title' => 'CX-9', 'parent_id' => 74],
            ['title' => 'MPV', 'parent_id' => 74],
            ['title' => 'MX-5 Miata', 'parent_id' => 74],
            ['title' => 'Premacy', 'parent_id' => 74],
            ['title' => 'RX 8', 'parent_id' => 74],
            ['title' => 'Tribute', 'parent_id' => 74],

            ['title' => 'MP4-12C', 'parent_id' => 75],

            ['title' => null, 'parent_id' => 76],

            ['title' => 'A 140', 'parent_id' => 77],
            ['title' => 'A 160', 'parent_id' => 77],
            ['title' => 'A 170', 'parent_id' => 77],
            ['title' => 'A 180', 'parent_id' => 77],
            ['title' => 'A 190', 'parent_id' => 77],
            ['title' => 'A 200', 'parent_id' => 77],
            ['title' => 'A 220', 'parent_id' => 77],
            ['title' => 'A 45 AMG', 'parent_id' => 77],
            ['title' => 'C 180', 'parent_id' => 77],
            ['title' => 'C 200', 'parent_id' => 77],
            ['title' => 'C 220', 'parent_id' => 77],
            ['title' => 'C 230', 'parent_id' => 77],
            ['title' => 'C 240', 'parent_id' => 77],
            ['title' => 'C 250', 'parent_id' => 77],
            ['title' => 'C 270', 'parent_id' => 77],
            ['title' => 'C 280', 'parent_id' => 77],
            ['title' => 'C 300', 'parent_id' => 77],
            ['title' => 'C 32 AMG', 'parent_id' => 77],
            ['title' => 'C 320', 'parent_id' => 77],
            ['title' => 'C 350', 'parent_id' => 77],
            ['title' => 'C 43 AMG', 'parent_id' => 77],
            ['title' => 'C 55 AMG', 'parent_id' => 77],
            ['title' => '200 D', 'parent_id' => 77],
            ['title' => '230 CE', 'parent_id' => 77],
            ['title' => 'E 180', 'parent_id' => 77],
            ['title' => 'E 200', 'parent_id' => 77],
            ['title' => 'E 220', 'parent_id' => 77],
            ['title' => 'E 230', 'parent_id' => 77],
            ['title' => 'E 240', 'parent_id' => 77],
            ['title' => 'E 250', 'parent_id' => 77],
            ['title' => 'E 260', 'parent_id' => 77],
            ['title' => 'E 270', 'parent_id' => 77],
            ['title' => 'E 280', 'parent_id' => 77],
            ['title' => 'E 290', 'parent_id' => 77],
            ['title' => 'E 300', 'parent_id' => 77],
            ['title' => 'E 320', 'parent_id' => 77],
            ['title' => 'E 350', 'parent_id' => 77],
            ['title' => 'E 400', 'parent_id' => 77],
            ['title' => 'E 43 AMG', 'parent_id' => 77],
            ['title' => 'E 430', 'parent_id' => 77],
            ['title' => 'E 63 AMG', 'parent_id' => 77],
            ['title' => 'G 230', 'parent_id' => 77],
            ['title' => 'G 270', 'parent_id' => 77],
            ['title' => 'G 300', 'parent_id' => 77],
            ['title' => 'G 320', 'parent_id' => 77],
            ['title' => 'G 350', 'parent_id' => 77],
            ['title' => 'G 400', 'parent_id' => 77],
            ['title' => 'G 500', 'parent_id' => 77],
            ['title' => 'G 55 AMG', 'parent_id' => 77],
            ['title' => 'G 63 AMG', 'parent_id' => 77],
            ['title' => 'G 65 AMG', 'parent_id' => 77],
            ['title' => 'B 170', 'parent_id' => 77],
            ['title' => 'B 180', 'parent_id' => 77],
            ['title' => 'B 200', 'parent_id' => 77],
            ['title' => 'CL 55 AMG', 'parent_id' => 77],
            ['title' => 'CL 550', 'parent_id' => 77],
            ['title' => 'CLS 250 CDI', 'parent_id' => 77],
            ['title' => 'CLS 350', 'parent_id' => 77],
            ['title' => 'CLS 450 Coupe', 'parent_id' => 77],
            ['title' => 'CLS 500', 'parent_id' => 77],
            ['title' => 'CLS 63 AMG', 'parent_id' => 77],
            ['title' => 'GL 320', 'parent_id' => 77],
            ['title' => 'GL 350', 'parent_id' => 77],
            ['title' => 'GL 400', 'parent_id' => 77],
            ['title' => 'GL 450', 'parent_id' => 77],
            ['title' => 'GL 500', 'parent_id' => 77],
            ['title' => 'GL 550', 'parent_id' => 77],
            ['title' => 'GL 63 AMG', 'parent_id' => 77],
            ['title' => 'GL Brabus Widestar', 'parent_id' => 77],
            ['title' => 'GLK 220', 'parent_id' => 77],
            ['title' => 'GLK 250', 'parent_id' => 77],
            ['title' => 'ML 250', 'parent_id' => 77],
            ['title' => 'ML 270', 'parent_id' => 77],
            ['title' => 'ML 280', 'parent_id' => 77],
            ['title' => 'ML 300', 'parent_id' => 77],
            ['title' => 'ML 320', 'parent_id' => 77],
            ['title' => 'ML 350', 'parent_id' => 77],
            ['title' => 'ML 400', 'parent_id' => 77],
            ['title' => 'ML 63 AMG', 'parent_id' => 77],
            ['title' => 'R 350', 'parent_id' => 77],
            ['title' => '280 SE', 'parent_id' => 77],
            ['title' => '280 SEL', 'parent_id' => 77],
            ['title' => '300 SEL', 'parent_id' => 77],
            ['title' => '400 SEL', 'parent_id' => 77],
            ['title' => '500 SEL', 'parent_id' => 77],
            ['title' => 'S 280', 'parent_id' => 77],
            ['title' => 'S 300', 'parent_id' => 77],
            ['title' => 'S 320', 'parent_id' => 77],
            ['title' => 'S 350', 'parent_id' => 77],
            ['title' => 'S 400', 'parent_id' => 77],
            ['title' => 'S 420', 'parent_id' => 77],
            ['title' => 'S 430', 'parent_id' => 77],
            ['title' => 'S 450', 'parent_id' => 77],
            ['title' => 'S 500', 'parent_id' => 77],
            ['title' => 'S 500 Coupe', 'parent_id' => 77],
            ['title' => 'S 55 AMG', 'parent_id' => 77],
            ['title' => 'S 550', 'parent_id' => 77],
            ['title' => 'S 560', 'parent_id' => 77],
            ['title' => 'S 600', 'parent_id' => 77],
            ['title' => 'S 63 AMG', 'parent_id' => 77],
            ['title' => 'S 63 AMG Coupe', 'parent_id' => 77],
            ['title' => 'S 65 AMG', 'parent_id' => 77],
            ['title' => 'S 65 AMG Coupe', 'parent_id' => 77],
            ['title' => 'SLK 200', 'parent_id' => 77],
            ['title' => 'SLK 230', 'parent_id' => 77],
            ['title' => 'SLK 250', 'parent_id' => 77],
            ['title' => 'SLS AMG', 'parent_id' => 77],
            ['title' => 'V 220', 'parent_id' => 77],
            ['title' => 'V 250', 'parent_id' => 77],
            ['title' => 'Viano', 'parent_id' => 77],
            ['title' => 'CLK 200', 'parent_id' => 77],
            ['title' => 'CLK 230', 'parent_id' => 77],
            ['title' => 'CLK 320', 'parent_id' => 77],
            ['title' => 'CLA 180', 'parent_id' => 77],
            ['title' => 'CLA 200', 'parent_id' => 77],
            ['title' => 'CLA 220', 'parent_id' => 77],
            ['title' => 'CLA 250', 'parent_id' => 77],
            ['title' => 'CLA 45 AMG', 'parent_id' => 77],
            ['title' => '1217', 'parent_id' => 77],
            ['title' => '207 D', 'parent_id' => 77],
            ['title' => '208 D', 'parent_id' => 77],
            ['title' => '210 D', 'parent_id' => 77],
            ['title' => '308 D', 'parent_id' => 77],
            ['title' => '403', 'parent_id' => 77],
            ['title' => '409 D', 'parent_id' => 77],
            ['title' => '410 D', 'parent_id' => 77],
            ['title' => '412 D', 'parent_id' => 77],
            ['title' => '508', 'parent_id' => 77],
            ['title' => '609 D', 'parent_id' => 77],
            ['title' => '612 D', 'parent_id' => 77],
            ['title' => '709 D', 'parent_id' => 77],
            ['title' => '809 D', 'parent_id' => 77],
            ['title' => '814 D', 'parent_id' => 77],
            ['title' => 'Actros 1840', 'parent_id' => 77],
            ['title' => 'Actros 1843', 'parent_id' => 77],
            ['title' => 'Actros 1844', 'parent_id' => 77],
            ['title' => 'Actros 2536', 'parent_id' => 77],
            ['title' => 'Actros 2544', 'parent_id' => 77],
            ['title' => 'Actros 2640', 'parent_id' => 77],
            ['title' => 'Actros 4140', 'parent_id' => 77],
            ['title' => 'Atego 1018', 'parent_id' => 77],
            ['title' => 'Atego 1217', 'parent_id' => 77],
            ['title' => 'Atego 1218', 'parent_id' => 77],
            ['title' => 'Atego 1222', 'parent_id' => 77],
            ['title' => 'Atego 1223', 'parent_id' => 77],
            ['title' => 'Atego 1228', 'parent_id' => 77],
            ['title' => 'Atego 1229', 'parent_id' => 77],
            ['title' => 'Atego 1517', 'parent_id' => 77],
            ['title' => 'Atego 1524', 'parent_id' => 77],
            ['title' => 'Atego 1528', 'parent_id' => 77],
            ['title' => 'Atego 1828', 'parent_id' => 77],
            ['title' => 'Atego 2528', 'parent_id' => 77],
            ['title' => 'Atego 813', 'parent_id' => 77],
            ['title' => 'Atego 814', 'parent_id' => 77],
            ['title' => 'Atego 815', 'parent_id' => 77],
            ['title' => 'Atego 816', 'parent_id' => 77],
            ['title' => 'Atego 817', 'parent_id' => 77],
            ['title' => 'Atego 818', 'parent_id' => 77],
            ['title' => 'Axor 1829', 'parent_id' => 77],
            ['title' => 'Axor 1840', 'parent_id' => 77],
            ['title' => 'Axor 1843', 'parent_id' => 77],
            ['title' => 'Axor 2533', 'parent_id' => 77],
            ['title' => 'Axor 2533', 'parent_id' => 77],
            ['title' => 'Axor 3028', 'parent_id' => 77],
            ['title' => 'MB140D', 'parent_id' => 77],
            ['title' => 'Travego', 'parent_id' => 77],
            ['title' => 'Vario', 'parent_id' => 77],
            ['title' => 'Sprinter 208', 'parent_id' => 77],
            ['title' => 'Sprinter 209', 'parent_id' => 77],
            ['title' => 'Sprinter 211', 'parent_id' => 77],
            ['title' => 'Sprinter 212', 'parent_id' => 77],
            ['title' => 'Sprinter 213', 'parent_id' => 77],
            ['title' => 'Sprinter 308', 'parent_id' => 77],
            ['title' => 'Sprinter 309', 'parent_id' => 77],
            ['title' => 'Sprinter 310', 'parent_id' => 77],
            ['title' => 'Sprinter 311', 'parent_id' => 77],
            ['title' => 'Sprinter 312', 'parent_id' => 77],
            ['title' => 'Sprinter 313', 'parent_id' => 77],
            ['title' => 'Sprinter 315', 'parent_id' => 77],
            ['title' => 'Sprinter 316', 'parent_id' => 77],
            ['title' => 'Sprinter 318', 'parent_id' => 77],
            ['title' => 'Sprinter 319', 'parent_id' => 77],
            ['title' => 'Sprinter 411', 'parent_id' => 77],
            ['title' => 'Sprinter 412', 'parent_id' => 77],
            ['title' => 'Sprinter 413', 'parent_id' => 77],
            ['title' => 'Sprinter 416', 'parent_id' => 77],
            ['title' => 'Sprinter 513', 'parent_id' => 77],
            ['title' => 'Sprinter 515', 'parent_id' => 77],
            ['title' => 'Sprinter 516', 'parent_id' => 77],
            ['title' => 'Sprinter 519', 'parent_id' => 77],
            ['title' => 'GLA 200', 'parent_id' => 77],
            ['title' => 'GLA 220', 'parent_id' => 77],
            ['title' => 'GLA 250', 'parent_id' => 77],
            ['title' => 'GLE 300', 'parent_id' => 77],
            ['title' => 'GLE 350', 'parent_id' => 77],
            ['title' => 'GLE 43 AMG', 'parent_id' => 77],
            ['title' => 'GLE 43 AMG Coupe ', 'parent_id' => 77],
            ['title' => 'GLE 450', 'parent_id' => 77],
            ['title' => 'GLE 450 AMG Coupe', 'parent_id' => 77],
            ['title' => 'GLE 53 AMG Coupe', 'parent_id' => 77],
            ['title' => 'GLE 63 AMG S', 'parent_id' => 77],
            ['title' => 'GLC 200 4Matic', 'parent_id' => 77],
            ['title' => 'GLC 200 4Matic Coupe', 'parent_id' => 77],
            ['title' => 'GLC 250', 'parent_id' => 77],
            ['title' => 'GLC 300', 'parent_id' => 77],
            ['title' => 'GLS 350', 'parent_id' => 77],
            ['title' => 'GLS 400', 'parent_id' => 77],
            ['title' => 'GLS 450', 'parent_id' => 77],
            ['title' => 'GLS 500', 'parent_id' => 77],
            ['title' => 'GLS 580', 'parent_id' => 77],
            ['title' => 'GLS 63 AMG', 'parent_id' => 77],
            ['title' => 'Vito', 'parent_id' => 77],
            ['title' => 'Vito 108', 'parent_id' => 77],
            ['title' => 'Vito 109', 'parent_id' => 77],
            ['title' => 'Vito 110', 'parent_id' => 77],
            ['title' => 'Vito 111', 'parent_id' => 77],
            ['title' => 'Vito 112', 'parent_id' => 77],
            ['title' => 'Vito 113', 'parent_id' => 77],
            ['title' => 'Vito 114', 'parent_id' => 77],
            ['title' => 'Vito 115', 'parent_id' => 77],
            ['title' => 'Vito 116', 'parent_id' => 77],
            ['title' => 'Vito 119', 'parent_id' => 77],
            ['title' => 'Vito 122', 'parent_id' => 77],
            ['title' => 'X 250D', 'parent_id' => 77],
            ['title' => 'AMG GT', 'parent_id' => 77],
            ['title' => 'AMG GT 43', 'parent_id' => 77],
            ['title' => 'AMG GT S', 'parent_id' => 77],
            ['title' => '100', 'parent_id' => 77],
            ['title' => '190', 'parent_id' => 77],
            ['title' => '200', 'parent_id' => 77],
            ['title' => '300', 'parent_id' => 77],
            ['title' => 'Citan', 'parent_id' => 77],
            ['title' => 'Gazelle', 'parent_id' => 77],
            ['title' => 'Vaneo', 'parent_id' => 77],

            ['title' => 'S 400', 'parent_id' => 78],
            ['title' => 'S 500', 'parent_id' => 78],
            ['title' => 'S 560', 'parent_id' => 78],
            ['title' => 'S 600', 'parent_id' => 78],

            ['title' => '3', 'parent_id' => 79],
            ['title' => '350', 'parent_id' => 79],
            ['title' => '5', 'parent_id' => 79],
            ['title' => '550', 'parent_id' => 79],
            ['title' => '6', 'parent_id' => 79],

            ['title' => 'Clubman', 'parent_id' => 80],
            ['title' => 'Cooper', 'parent_id' => 80],
            ['title' => 'Countryman', 'parent_id' => 80],

            ['title' => '3.112.12', 'parent_id' => 81],

            ['title' => 'Airtrek', 'parent_id' => 82],
            ['title' => 'ASX', 'parent_id' => 82],
            ['title' => 'Attrage', 'parent_id' => 82],
            ['title' => 'Chariot', 'parent_id' => 82],
            ['title' => 'Colt', 'parent_id' => 82],
            ['title' => 'Eclipse Cross', 'parent_id' => 82],
            ['title' => 'Galant', 'parent_id' => 82],
            ['title' => 'Grandis', 'parent_id' => 82],
            ['title' => 'L 200', 'parent_id' => 82],
            ['title' => 'L 300', 'parent_id' => 82],
            ['title' => 'Lancer', 'parent_id' => 82],
            ['title' => 'Mirage', 'parent_id' => 82],
            ['title' => 'Outlander', 'parent_id' => 82],
            ['title' => 'Outlander Sport', 'parent_id' => 82],
            ['title' => 'Pajero', 'parent_id' => 82],
            ['title' => 'Pajero io', 'parent_id' => 82],
            ['title' => 'Pajero Pinin', 'parent_id' => 82],
            ['title' => 'Pajero Sport', 'parent_id' => 82],
            ['title' => 'Rosa', 'parent_id' => 82],
            ['title' => 'Space Runner', 'parent_id' => 82],
            ['title' => 'Space Wagon', 'parent_id' => 82],

            ['title' => '100 SFC Snappy X', 'parent_id' => 83],
            ['title' => '125 NT TURKUAZ', 'parent_id' => 83],
            ['title' => '125 ZNU', 'parent_id' => 83],
            ['title' => '150 MASH', 'parent_id' => 83],
            ['title' => '50 Revival', 'parent_id' => 83],
            ['title' => 'Ritmica 110', 'parent_id' => 83],
            ['title' => 'X-Treme MAXX - 200', 'parent_id' => 83],

            ['title' => '2140', 'parent_id' => 84],
            ['title' => '2141', 'parent_id' => 84],
            ['title' => '2715', 'parent_id' => 84],
            ['title' => '400', 'parent_id' => 84],
            ['title' => '403', 'parent_id' => 84],
            ['title' => '408', 'parent_id' => 84],
            ['title' => '412', 'parent_id' => 84],

            ['title' => 'Muravey- 2 01', 'parent_id' => 85],
            ['title' => 'TG200', 'parent_id' => 85],
            ['title' => 'TGA200-01P', 'parent_id' => 85],

            ['title' => '48-2', 'parent_id' => 86],

            ['title' => 'Cityliner', 'parent_id' => 87],

            ['title' => 'NP150ZH-E', 'parent_id' => 88],

            ['title' => '350Z', 'parent_id' => 89],
            ['title' => 'Almera', 'parent_id' => 89],
            ['title' => 'Altima', 'parent_id' => 89],
            ['title' => 'Armada', 'parent_id' => 89],
            ['title' => 'Bluebird', 'parent_id' => 89],
            ['title' => 'Juke', 'parent_id' => 89],
            ['title' => 'Kicks', 'parent_id' => 89],
            ['title' => 'Leaf', 'parent_id' => 89],
            ['title' => 'March', 'parent_id' => 89],
            ['title' => 'Maxima', 'parent_id' => 89],
            ['title' => 'Micra', 'parent_id' => 89],
            ['title' => 'Murano', 'parent_id' => 89],
            ['title' => 'Navara', 'parent_id' => 89],
            ['title' => 'Note', 'parent_id' => 89],
            ['title' => 'Pathfinder', 'parent_id' => 89],
            ['title' => 'Patrol', 'parent_id' => 89],
            ['title' => 'Presage', 'parent_id' => 89],
            ['title' => 'Primera', 'parent_id' => 89],
            ['title' => 'Qashqai', 'parent_id' => 89],
            ['title' => 'Rogue', 'parent_id' => 89],
            ['title' => 'Sentra', 'parent_id' => 89],
            ['title' => 'Serena', 'parent_id' => 89],
            ['title' => 'Sunny', 'parent_id' => 89],
            ['title' => 'Teana', 'parent_id' => 89],
            ['title' => 'Terrano', 'parent_id' => 89],
            ['title' => 'Tiida', 'parent_id' => 89],
            ['title' => 'Urvan', 'parent_id' => 89],
            ['title' => 'Vanette', 'parent_id' => 89],
            ['title' => 'Versa', 'parent_id' => 89],
            ['title' => 'X-Trail', 'parent_id' => 89],
            ['title' => 'Xterra', 'parent_id' => 89],

            ['title' => 'Agila', 'parent_id' => 90],
            ['title' => 'Antara', 'parent_id' => 90],
            ['title' => 'Astra', 'parent_id' => 90],
            ['title' => 'Combo', 'parent_id' => 90],
            ['title' => 'Corsa', 'parent_id' => 90],
            ['title' => 'Frontera', 'parent_id' => 90],
            ['title' => 'Insignia', 'parent_id' => 90],
            ['title' => 'Kadett', 'parent_id' => 90],
            ['title' => 'Meriva', 'parent_id' => 90],
            ['title' => 'Omega', 'parent_id' => 90],
            ['title' => 'Signum', 'parent_id' => 90],
            ['title' => 'Sintra', 'parent_id' => 90],
            ['title' => 'Tigra', 'parent_id' => 90],
            ['title' => 'Vectra', 'parent_id' => 90],
            ['title' => 'Vita', 'parent_id' => 90],
            ['title' => 'Vivaro', 'parent_id' => 90],
            ['title' => 'Zafira', 'parent_id' => 90],

            ['title' => 'Doruk 220 T', 'parent_id' => 91],

            ['title' => '32054', 'parent_id' => 92],

            ['title' => '206', 'parent_id' => 93],
            ['title' => '207', 'parent_id' => 93],
            ['title' => '301', 'parent_id' => 93],
            ['title' => '306', 'parent_id' => 93],
            ['title' => '307', 'parent_id' => 93],
            ['title' => '307 CC', 'parent_id' => 93],
            ['title' => '308', 'parent_id' => 93],
            ['title' => '308 CC', 'parent_id' => 93],
            ['title' => '405', 'parent_id' => 93],
            ['title' => '406', 'parent_id' => 93],
            ['title' => '407', 'parent_id' => 93],
            ['title' => '607', 'parent_id' => 93],
            ['title' => 'J9', 'parent_id' => 93],
            ['title' => 'Khazar 406', 'parent_id' => 93],
            ['title' => 'Pars', 'parent_id' => 93],
            ['title' => 'Partner', 'parent_id' => 93],
            ['title' => 'RCZ', 'parent_id' => 93],

            ['title' => 'X10', 'parent_id' => 94],

            ['title' => 'Solstice', 'parent_id' => 95],

            ['title' => '718 Boxter', 'parent_id' => 96],
            ['title' => '718 Boxter S', 'parent_id' => 96],
            ['title' => '911 Carrera', 'parent_id' => 96],
            ['title' => '911 Carrera 4S', 'parent_id' => 96],
            ['title' => '911 Turbo', 'parent_id' => 96],
            ['title' => 'Panamera', 'parent_id' => 96],
            ['title' => 'Panamera 4', 'parent_id' => 96],
            ['title' => 'Panamera 4S', 'parent_id' => 96],
            ['title' => 'Panamera GTS', 'parent_id' => 96],
            ['title' => 'Panamera S', 'parent_id' => 96],
            ['title' => 'Panamera Turbo', 'parent_id' => 96],
            ['title' => 'Panamera Turbo Executive', 'parent_id' => 96],
            ['title' => 'Panamera Turbo S', 'parent_id' => 96],
            ['title' => 'Macan', 'parent_id' => 96],
            ['title' => 'Macan S', 'parent_id' => 96],
            ['title' => 'Macan Turbo', 'parent_id' => 96],
            ['title' => 'Cayenne', 'parent_id' => 96],
            ['title' => 'Cayenne Coupe', 'parent_id' => 96],
            ['title' => 'Cayenne E-Hybrid', 'parent_id' => 96],
            ['title' => 'Cayenne GTS', 'parent_id' => 96],
            ['title' => 'Cayenne S', 'parent_id' => 96],
            ['title' => 'Cayenne Turbo', 'parent_id' => 96],
            ['title' => 'Cayenne Turbo Coupe', 'parent_id' => 96],
            ['title' => 'Cayenne Turbo S', 'parent_id' => 96],
            ['title' => 'Cayenne Turbo S E-Hybrid', 'parent_id' => 96],
            ['title' => 'Boxster', 'parent_id' => 96],

            ['title' => 'Gentra', 'parent_id' => 97],
            ['title' => 'Nexia R3', 'parent_id' => 97],
            ['title' => 'R2', 'parent_id' => 97],
            ['title' => 'R4', 'parent_id' => 97],

            ['title' => '11', 'parent_id' => 98],
            ['title' => '12 Toros', 'parent_id' => 98],
            ['title' => '19', 'parent_id' => 98],
            ['title' => '21', 'parent_id' => 98],
            ['title' => 'Arkana', 'parent_id' => 98],
            ['title' => 'Clio', 'parent_id' => 98],
            ['title' => 'Dokker', 'parent_id' => 98],
            ['title' => 'Duster', 'parent_id' => 98],
            ['title' => 'Espace', 'parent_id' => 98],
            ['title' => 'Fluence', 'parent_id' => 98],
            ['title' => 'Grand Scenic', 'parent_id' => 98],
            ['title' => 'Kangoo', 'parent_id' => 98],
            ['title' => 'Koleos', 'parent_id' => 98],
            ['title' => 'Laguna', 'parent_id' => 98],
            ['title' => 'Logan', 'parent_id' => 98],
            ['title' => 'Magnum', 'parent_id' => 98],
            ['title' => 'Master', 'parent_id' => 98],
            ['title' => 'Megane', 'parent_id' => 98],
            ['title' => 'Megane Scenic', 'parent_id' => 98],
            ['title' => 'Modus', 'parent_id' => 98],
            ['title' => 'Premium 420', 'parent_id' => 98],
            ['title' => 'Sandero', 'parent_id' => 98],
            ['title' => 'Scenic', 'parent_id' => 98],
            ['title' => 'Symbol', 'parent_id' => 98],
            ['title' => 'Tondar', 'parent_id' => 98],
            ['title' => 'Trafic', 'parent_id' => 98],

            ['title' => 'Cullinan', 'parent_id' => 99],
            ['title' => 'Phantom', 'parent_id' => 99],
            ['title' => 'Wraith', 'parent_id' => 99],

            ['title' => '200', 'parent_id' => 100],
            ['title' => '75', 'parent_id' => 100],

            ['title' => '9-3', 'parent_id' => 101],
            ['title' => '9-5', 'parent_id' => 101],

            ['title' => '132', 'parent_id' => 102],
            ['title' => '141', 'parent_id' => 102],
            ['title' => 'Saina', 'parent_id' => 102],
            ['title' => 'Tiba', 'parent_id' => 102],

            ['title' => 'G 420', 'parent_id' => 103],

            ['title' => 'Cordoba', 'parent_id' => 104],
            ['title' => 'Exeo', 'parent_id' => 104],
            ['title' => 'Ibiza', 'parent_id' => 104],
            ['title' => 'Leon', 'parent_id' => 104],
            ['title' => 'Toledo', 'parent_id' => 104],

            ['title' => 'F2000', 'parent_id' => 105],
            ['title' => 'F3000', 'parent_id' => 105],

            ['title' => 'SLG 6602', 'parent_id' => 106],

            ['title' => 'Fabia', 'parent_id' => 107],
            ['title' => 'Felicia', 'parent_id' => 107],
            ['title' => 'Kamiq', 'parent_id' => 107],
            ['title' => 'Karoq', 'parent_id' => 107],
            ['title' => 'Kodiaq', 'parent_id' => 107],
            ['title' => 'Octavia', 'parent_id' => 107],
            ['title' => 'Rapid', 'parent_id' => 107],
            ['title' => 'Scala', 'parent_id' => 107],
            ['title' => 'Superb', 'parent_id' => 107],
            ['title' => 'Yeti', 'parent_id' => 107],

            ['title' => 'Forfour', 'parent_id' => 108],
            ['title' => 'Fortwo', 'parent_id' => 108],

            ['title' => 'Actyon', 'parent_id' => 109],
            ['title' => 'Actyon Sports', 'parent_id' => 109],
            ['title' => 'Korando', 'parent_id' => 109],
            ['title' => 'Kyron', 'parent_id' => 109],
            ['title' => 'Rexton', 'parent_id' => 109],

            ['title' => 'B9 Tribeca', 'parent_id' => 110],
            ['title' => 'Forester', 'parent_id' => 110],
            ['title' => 'Impreza', 'parent_id' => 110],
            ['title' => 'Legacy', 'parent_id' => 110],
            ['title' => 'Outback', 'parent_id' => 110],
            ['title' => 'Tribeca', 'parent_id' => 110],
            ['title' => '5XV', 'parent_id' => 110],

            ['title' => 'AN 200', 'parent_id' => 111],
            ['title' => 'Boulevard', 'parent_id' => 111],
            ['title' => 'GSR 750', 'parent_id' => 111],
            ['title' => 'Intruder M1800R', 'parent_id' => 111],
            ['title' => 'Kingquad 500', 'parent_id' => 111],
            ['title' => 'V-Strom 650', 'parent_id' => 111],
            ['title' => 'Aerio', 'parent_id' => 111],
            ['title' => 'Grand Vitara', 'parent_id' => 111],
            ['title' => 'GW 250', 'parent_id' => 111],
            ['title' => 'Jimny', 'parent_id' => 111],
            ['title' => 'Kizashi', 'parent_id' => 111],
            ['title' => 'Splash', 'parent_id' => 111],
            ['title' => 'Swift', 'parent_id' => 111],
            ['title' => 'SX4', 'parent_id' => 111],

            ['title' => 'Indica', 'parent_id' => 112],

            ['title' => 'Model S', 'parent_id' => 113],

            ['title' => 'Dogan', 'parent_id' => 114],
            ['title' => 'Kartal', 'parent_id' => 114],
            ['title' => 'Sahin', 'parent_id' => 114],

            ['title' => 'Auris', 'parent_id' => 115],
            ['title' => 'Avalon', 'parent_id' => 115],
            ['title' => 'Avensis', 'parent_id' => 115],
            ['title' => 'C-HR', 'parent_id' => 115],
            ['title' => 'Camry', 'parent_id' => 115],
            ['title' => 'Carina', 'parent_id' => 115],
            ['title' => 'Corolla', 'parent_id' => 115],
            ['title' => 'Corolla Verso', 'parent_id' => 115],
            ['title' => 'FJ Cruiser', 'parent_id' => 115],
            ['title' => 'Fortuner', 'parent_id' => 115],
            ['title' => 'GT 86', 'parent_id' => 115],
            ['title' => 'Harrier', 'parent_id' => 115],
            ['title' => 'HiAce', 'parent_id' => 115],
            ['title' => 'Highlander', 'parent_id' => 115],
            ['title' => 'Hilux', 'parent_id' => 115],
            ['title' => 'IQ', 'parent_id' => 115],
            ['title' => 'Land Cruiser', 'parent_id' => 115],
            ['title' => 'Prado', 'parent_id' => 115],
            ['title' => 'Previa', 'parent_id' => 115],
            ['title' => 'Prius', 'parent_id' => 115],
            ['title' => 'Prius C', 'parent_id' => 115],
            ['title' => 'Prius V', 'parent_id' => 115],
            ['title' => 'RAV 4', 'parent_id' => 115],
            ['title' => 'Sequoia', 'parent_id' => 115],
            ['title' => 'Sienna', 'parent_id' => 115],
            ['title' => 'Solara', 'parent_id' => 115],
            ['title' => 'Supra', 'parent_id' => 115],
            ['title' => 'Surf', 'parent_id' => 115],
            ['title' => 'Tacoma', 'parent_id' => 115],
            ['title' => 'Venza', 'parent_id' => 115],
            ['title' => 'Vitz', 'parent_id' => 115],
            ['title' => 'Yaris', 'parent_id' => 115],

            ['title' => '31512', 'parent_id' => 116],
            ['title' => '31514', 'parent_id' => 116],
            ['title' => '31519', 'parent_id' => 116],
            ['title' => '3162', 'parent_id' => 116],
            ['title' => '3303', 'parent_id' => 116],
            ['title' => '39625', 'parent_id' => 116],
            ['title' => '452', 'parent_id' => 116],
            ['title' => '462', 'parent_id' => 116],
            ['title' => '469', 'parent_id' => 116],
            ['title' => 'Hunter', 'parent_id' => 116],
            ['title' => 'Patriot', 'parent_id' => 116],
            ['title' => 'Pickup', 'parent_id' => 116],
            ['title' => 'Profi', 'parent_id' => 116],

            ['title' => '4320', 'parent_id' => 117],
            ['title' => 'DNEPR MT', 'parent_id' => 117],

            ['title' => 'Primavera 50', 'parent_id' => 118],

            ['title' => 'Amarok', 'parent_id' => 119],
            ['title' => 'Arteon', 'parent_id' => 119],
            ['title' => 'Beetle', 'parent_id' => 119],
            ['title' => 'Bora', 'parent_id' => 119],
            ['title' => 'Caddy', 'parent_id' => 119],
            ['title' => 'Caravelle', 'parent_id' => 119],
            ['title' => 'Crafter', 'parent_id' => 119],
            ['title' => 'Fox', 'parent_id' => 119],
            ['title' => 'Golf', 'parent_id' => 119],
            ['title' => 'Golf GTI', 'parent_id' => 119],
            ['title' => 'Golf Plus', 'parent_id' => 119],
            ['title' => 'Jetta', 'parent_id' => 119],
            ['title' => 'Multivan', 'parent_id' => 119],
            ['title' => 'Passat', 'parent_id' => 119],
            ['title' => 'Passat CC', 'parent_id' => 119],
            ['title' => 'Phaeton', 'parent_id' => 119],
            ['title' => 'Polo', 'parent_id' => 119],
            ['title' => 'Scirocco', 'parent_id' => 119],
            ['title' => 'Sharan', 'parent_id' => 119],
            ['title' => 'Tiguan', 'parent_id' => 119],
            ['title' => 'Touareg', 'parent_id' => 119],
            ['title' => 'Touran', 'parent_id' => 119],
            ['title' => 'Transporter', 'parent_id' => 119],
            ['title' => 'Vento', 'parent_id' => 119],

            ['title' => '240', 'parent_id' => 120],
            ['title' => '850', 'parent_id' => 120],
            ['title' => '940', 'parent_id' => 120],
            ['title' => 'C 70', 'parent_id' => 120],
            ['title' => 'FH 13', 'parent_id' => 120],
            ['title' => 'S 40', 'parent_id' => 120],
            ['title' => 'S 60', 'parent_id' => 120],
            ['title' => 'S 70', 'parent_id' => 120],
            ['title' => 'S 80', 'parent_id' => 120],
            ['title' => 'S 90', 'parent_id' => 120],
            ['title' => 'V 90', 'parent_id' => 120],
            ['title' => 'XC 40', 'parent_id' => 120],
            ['title' => 'XC 60', 'parent_id' => 120],
            ['title' => 'XC 70', 'parent_id' => 120],
            ['title' => 'XC 90', 'parent_id' => 120],

            ['title' => '2', 'parent_id' => 121],

            ['title' => 'Grizzly 660', 'parent_id' => 122],
            ['title' => 'R15', 'parent_id' => 122],
            ['title' => 'Ray Z 115', 'parent_id' => 122],
            ['title' => 'RAY-ZR', 'parent_id' => 122],
            ['title' => 'Vino', 'parent_id' => 122],

            ['title' => '965', 'parent_id' => 123],
            ['title' => '968M', 'parent_id' => 123],
            ['title' => 'Slavuta', 'parent_id' => 123],
            ['title' => 'Tavriya', 'parent_id' => 123],
            ['title' => 'Vida', 'parent_id' => 123],

            ['title' => '130', 'parent_id' => 124],
            ['title' => '131', 'parent_id' => 124],
            ['title' => '133', 'parent_id' => 124],
            ['title' => '157', 'parent_id' => 124],
            ['title' => '4334', 'parent_id' => 124],
            ['title' => '5301', 'parent_id' => 124],
            ['title' => 'MMZ 45023', 'parent_id' => 124],

            ['title' => 'Spex', 'parent_id' => 125],

            ['title' => 'Panther ZT150-8A', 'parent_id' => 126],
            ['title' => 'R310', 'parent_id' => 126],
            ['title' => 'Tiger ZT150-3A', 'parent_id' => 126],

        ];
        foreach($types as $c){
            Type::create([
                'title' => $c['title'],
                'parent_id' => $c['parent_id'],
            ]);
        }

        $motor = [
            ['motor' => 50],
            ['motor' => 100],
            ['motor' => 150],
            ['motor' => 200],
            ['motor' => 250],
            ['motor' => 300],
            ['motor' => 350],
            ['motor' => 400],
            ['motor' => 450],
            ['motor' => 500],
            ['motor' => 600],
            ['motor' => 700],
            ['motor' => 800],
            ['motor' => 900],
            ['motor' => 1000],
            ['motor' => 1100],
            ['motor' => 1200],
            ['motor' => 1300],
            ['motor' => 1400],
            ['motor' => 1500],
            ['motor' => 1600],
            ['motor' => 1700],
            ['motor' => 1800],
            ['motor' => 1900],
            ['motor' => 2000],
            ['motor' => 2100],
            ['motor' => 2200],
            ['motor' => 2300],
            ['motor' => 2400],
            ['motor' => 2500],
            ['motor' => 2600],
            ['motor' => 2700],
            ['motor' => 2800],
            ['motor' => 2900],
            ['motor' => 3000],
            ['motor' => 3100],
            ['motor' => 3200],
            ['motor' => 3300],
            ['motor' => 3400],
            ['motor' => 3500],
            ['motor' => 3600],
            ['motor' => 3700],
            ['motor' => 3800],
            ['motor' => 3900],
            ['motor' => 4000],
            ['motor' => 4100],
            ['motor' => 4200],
            ['motor' => 4300],
            ['motor' => 4400],
            ['motor' => 4500],
            ['motor' => 4600],
            ['motor' => 4700],
            ['motor' => 4800],
            ['motor' => 4900],
            ['motor' => 5000],
            ['motor' => 5100],
            ['motor' => 5200],
            ['motor' => 5300],
            ['motor' => 5400],
            ['motor' => 5500],
            ['motor' => 5600],
            ['motor' => 5700],
            ['motor' => 5800],
            ['motor' => 5900],
            ['motor' => 6000],
            ['motor' => 6100],
            ['motor' => 6200],
            ['motor' => 6300],
            ['motor' => 6400],
            ['motor' => 6500],
            ['motor' => 7000],
            ['motor' => 7500],
            ['motor' => 8000],
            ['motor' => 8500],
            ['motor' => 9000],
            ['motor' => 9500],
            ['motor' => 10000],
            ['motor' => 11000],
            ['motor' => 12000],
            ['motor' => 13000],
            ['motor' => 14000],
            ['motor' => 15000],
            ['motor' => 16000],
        ];
        foreach($motor as $c){
            Motor::create([
                'motor' => $c['motor'],
            ]);
        }

        $year = [
            ['year' => 2020],
            ['year' => 2019],
            ['year' => 2018],
            ['year' => 2017],
            ['year' => 2016],
            ['year' => 2015],
            ['year' => 2014],
            ['year' => 2013],
            ['year' => 2012],
            ['year' => 2011],
            ['year' => 2010],
            ['year' => 2009],
            ['year' => 2008],
            ['year' => 2007],
            ['year' => 2006],
            ['year' => 2005],
            ['year' => 2004],
            ['year' => 2003],
            ['year' => 2002],
            ['year' => 2001],
            ['year' => 2000],
            ['year' => 1999],
            ['year' => 1998],
            ['year' => 1997],
            ['year' => 1996],
            ['year' => 1995],
            ['year' => 1994],
            ['year' => 1993],
            ['year' => 1992],
            ['year' => 1991],
            ['year' => 1990],
            ['year' => 1989],
            ['year' => 1988],
            ['year' => 1987],
            ['year' => 1986],
            ['year' => 1985],
            ['year' => 1984],
            ['year' => 1983],
            ['year' => 1982],
            ['year' => 1981],
            ['year' => 1980],
            ['year' => 1979],
            ['year' => 1978],
            ['year' => 1977],
            ['year' => 1976],
            ['year' => 1975],
            ['year' => 1974],
            ['year' => 1973],
            ['year' => 1972],
            ['year' => 1971],
            ['year' => 1970],
            ['year' => 1969],
            ['year' => 1968],
            ['year' => 1967],
            ['year' => 1966],
            ['year' => 1965],
            ['year' => 1964],
            ['year' => 1963],
            ['year' => 1962],
            ['year' => 1961],
            ['year' => 1960],
        ];
        foreach($year as $c){
            Year::create([
                'year' => $c['year'],
            ]);
        }

        $cities = [
            ['city' => 'Ağdam'],
            ['city' => 'Ağdaş'],
            ['city' => 'Ağca,bədi'],
            ['city' => 'Hacıqabul'],
            ['city' => 'Ağstafa'],
            ['city' => 'Astara'],
            ['city' => 'Ağsu'],
            ['city' => 'Bakı'],
            ['city' => 'Bərdə'],
            ['city' => 'Beyləqan'],
            ['city' => 'Balakən'],
            ['city' => 'Biləsuvar'],
            ['city' => 'Qəbələ'],
            ['city' => 'Qax'],
            ['city' => 'Göyçay'],
            ['city' => 'Goranboy'],
            ['city' => 'Qobustan'],
            ['city' => 'Gəncə'],
            ['city' => 'Göygöl'],
            ['city' => 'Dəliməmmədli'],
            ['city' => 'Daşkəsən'],
            ['city' => 'Cəlilabad'],
            ['city' => 'Cəbrayıl'],
            ['city' => 'Culfa'],
            ['city' => 'Yevlax'],
            ['city' => 'Zaqatala'],
            ['city' => 'Zərdab'],
            ['city' => 'İmişli'],
            ['city' => 'İsmayıllı'],
            ['city' => 'Qazax'],
            ['city' => 'Gədəbəy'],
            ['city' => 'Quba'],
            ['city' => 'Qusar'],
            ['city' => 'Kürdəmir'],
            ['city' => 'Lənkəran'],
            ['city' => 'Lerik'],
            ['city' => 'Liman'],
            ['city' => 'Masallı'],
            ['city' => 'Mingəçevir'],
            ['city' => 'Naftalan'],
            ['city' => 'Naxçıvan'],
            ['city' => 'Neftçala'],
            ['city' => 'Oğuz',],
            ['city' => 'Ordubad'],
            ['city' => 'Saatlı'],
            ['city' => 'Sabirabad'],
            ['city' => 'Salyan'],
            ['city' => 'Samux'],
            ['city' => 'Siyəzən'],
            ['city' => 'Sumqayıt'],
            ['city' => 'Tovuz'],
            ['city' => 'Tərtər'],
            ['city' => 'Ucar'],
            ['city' => 'Füzuli'],
            ['city' => 'Xaçmaz'],
            ['city' => 'Xudat'],
            ['city' => 'Xızı'],
            ['city' => 'Xırdalan'],
            ['city' => 'Şabran'],
            ['city' => 'Şəmkir'],
            ['city' => 'Şərur'],
            ['city' => 'Şəki' ],
            ['city' => 'Şamaxı'],
            ['city' => 'Şirvan'],
            ['city' => 'Yardım']
        ];
        foreach($cities as $c){
            City::create([
                'city' => $c['city'],
            ]);
        }

        $status = [
            ['status' => 'Alıcı'],
            ['status' => 'Satıcı'],
            ['status' => 'Hamısı'],
        ];
        foreach($status as $c){
            Status::create([
                'status' => $c['status'],
            ]);
        }

        $who = [
            ['who' => 'Mağaza'],
            ['who' => 'Ölüxana'],
            ['who' => 'Hər ikisi'],
        ];
        foreach($who as $c){
            Who::create([
                'who' => $c['who'],
            ]);
        }

        $fuel_types = [
            ['title' => 'Benzin'],
            ['title' => 'Dizel'],
            ['title' => 'Qaz'],
            ['title' => 'Hibrid'],
            ['title' => 'Elektron'],
        ];
        foreach($fuel_types as $c){
            FuelType::create([
                'title' => $c['title'],
            ]);
        }

        $condition = [
            ['title' => 'Yeni'],
            ['title' => 'Az işlənmiş'],
            ['title' => 'İşlənmiş'],
            ['title' => 'Normal'],
            ['title' => 'Köhnə'],
            ['title' => 'Fərqi yoxdu'],
        ];
        foreach($condition as $c){
            Condition::create([
                'title' => $c['title'],
            ]);
        }
    }
}
